### ISSUE TITLE
chrome net::ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY

### ISSUE THREAD

**Issue by whitecolor** [molnarg/node-http2#101]
I'm tryting to use 3.0.0 (with h2-14) and latest Chrome with SPDY4 enabled

Chrome gives an error
net::ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY

I'm using self signed SSL certs.

Is it expected?

**Comment by justinfagnani** [comment]
I'm hitting this problem too, but only on Chrome Canary.

**Comment by todesschaf** [comment]
Yes, this is all to be expected - due to limitations in the node + openssl combo, it's pretty much impossible to order cipher suites correctly so that we negotiate an acceptable cipher suite. This may actually work in node >= 0.12, though, I haven't tested recently.

Maybe one of these days I'll verify that or get a patch submitted to node to allow proper cipher suite selection. Until that day, you'll have to figure out if chrome has an option to disable the TLS checks in h2 (I don't see one in chrome://flags, but perhaps there's another, more hidden set of options I don't know about, as I'm not usually a chrome user)

**Comment by justinfagnani** [comment]
Can you add something to the docs, maybe a pointer to this issue for node? I spent a lot of time trying to figure this out. Thanks!
