### ISSUE TITLE
Unable to use Chrome as a client for basic node-http2 server

### ISSUE THREAD

**Issue by monmohan** [molnarg/node-http2#114]
Hi
When using node-http2 server with chrome, request negotiation fails and the next protocol (post handshake) is always negotiated to HTTP/1.1. A similar program in golang works fine.
The details are here http://stackoverflow.com/questions/29885873/see-multiple-tcp-connections-when-using-http-2-from-chrome-to-node-http2-server.
Thanks
Monmohan

**Comment by OrKoN** [comment]
I support the question. What needs to be done in order to support Chrome as the client?

**Comment by brillout** [comment]
@molnarg any updates on that?

**Comment by molnarg** [comment]
Three thing you might want to try:

1. using a real cert instead a of a self signed one
2. try this node fork with ALPN support: https://github.com/shigeki/node/tree/alpn_support
3. Try io.js instead of node.js

I'm not up to date with the state of ALPN support in node.js or io.js, but the last version I've checked only support NPN. This might cause problems when negotiating HTTP2.

**Comment by kwela** [comment]
I've tried io.js and it worked.
